### ISSUE TITLE
removed accidentally created builds

### ISSUE THREAD

**Issue by phobson** [conda-forge/mpl-probscale-feedstock#9]
I accidentally pushed to master. Luckily the builds are good, but are associated with the wrong tag.

*Mea culpa*.

In any case, I think we should remove the builds from anaconda.org:
https://anaconda.org/conda-forge/mpl-probscale/files?version=0.2.2rc1

What's the process for this?
cc: @ocefpaf

**Comment by ocefpaf** [comment]
Unforgivable crime!! You are now banned forever from `conda-forge` :stuck_out_tongue_winking_eye: 

I can remove them right now. Don't worry. Unfortunately access to the channel is centralized b/c of the way anaconda.cloud works.
